name: Publish

on:
  push:
    branches:
      - develop

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Gatsby Publish
      uses: enriikke/gatsby-gh-pages-action@2.1.1
      with:
        access-token: $GITHUB_TOKEN
